@HOST=http://127.0.0.1:4002/api/user-service

###
GET {{HOST}}/user/661f811db81640477dbc41c5
content-type: application/json

###
GET {{HOST}}/users?page=-1&limit=10
content-type: application/json

###
POST {{HOST}}/user
content-type: application/json

{
    "name": "Arjun T",
    "email": "arjun@gmail.com",
    "mobile": "9632587410",
    "password": "123456",
    "role": [1001, 1002],
    "outlet": "Outlet 10",
    "createdBy": "654b2510725776204f2b3eef"
}

###
PATCH {{HOST}}/user
content-type: application/json

{
    "userId": "6617cfd9f26061dd4f639e04",
    "isActive": false,
    "password":"123456"
}

###
DELETE {{HOST}}/user/661e0bb63d6413e17ac4e80d
content-type: application/json